name: Build application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '6.0.x'
  SBOM_PN: 'SbomDemoApplication'
  SBOM_PV: '1.0.0'
  SBOM_PS: 'David Ullrich Software'
  SBOM_NSB: 'https://ullrich-software.at/github'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: |
          cd ./WebApplication1
          dotnet build -c Release -o ../bin --no-restore
          dotnet publish -c Release -o ../dotnet-webapp -r linux-x64 --self-contained true /p:UseAppHost=true

      - name: Generate SBOM
        run: |
          mkdir ./dotnet-webapp/sbom
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b ./dotnet-webapp -bc ./ -pn ${{ env.SBOM_PV }} -pv ${{ env.SBOM_PV }} -ps ${{ env.SBOM_PS }} -nsb ${{ env.SBOM_NSB }} -m ./dotnet-webapp/sbom -V Verbose

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./dotnet-webapp
